### ISSUE TITLE
Error in can-compile-brunch - "You probably need to execute `npm install` ..."

### ISSUE THREAD

**Issue by ninapavlich** [aldoivan/brunch-with-can#1]
I am installing a previously working brunch project on a new machine, I'm running into an error in the can-compile-brunch module:

```
➜  kiosk git:(lib-updates) ✗ brunch watch
/usr/local/lib/node_modules/brunch/lib/watch.js:447
      throw new Error("You probably need to execute `npm install` to insta
            ^
Error: You probably need to execute `npm install` to install brunch plugins. SyntaxError:     /Users/nina/Documents/Sites/MyGreatKiosk/kiosk/node_modules/can-compile-brunch/node_modules/can-    compile/node_modules/jsdom/lib/jsdom/level1/core.js:432
  set nodeName() { throw new core.DOMException();},
               ^
Unexpected token )
  at /usr/local/lib/node_modules/brunch/lib/watch.js:447:17
  at Array.map (native)
  at loadDeps (/usr/local/lib/node_modules/brunch/lib/watch.js:432:8)
  at loadPackages (/usr/local/lib/node_modules/brunch/lib/watch.js:452:13)
  at /usr/local/lib/node_modules/brunch/lib/watch.js:472:17
  at /usr/local/lib/node_modules/brunch/lib/helpers.js:604:12
  at /usr/local/lib/node_modules/brunch/lib/helpers.js:565:16
  at /usr/local/lib/node_modules/brunch/lib/helpers.js:511:12
  at /usr/local/lib/node_modules/brunch/node_modules/read-components/index.js:263:16
  at /usr/local/lib/node_modules/brunch/node_modules/read-components/index.js:72:14
  at FSReqWrap.cb [as oncomplete] (fs.js:226:19)
```

It appears that this is thrown by the jsdom library in can-compile-brunch.

My library versions are:
osx = 10.9.5
brunch = 1.8.5
npm = 2.12.1

The contents of my package.json

```
{
  "author": "Me",
  "name": "mgk",
  "description": "My Great Kiosk",
  "version": "0.0.1",
  "homepage": "",
  "private": true,
  "repository": {
    "type": "git",
    "url": "https://github.com/me/mgk"
  },
  "scripts": {
    "start": "brunch watch --server",
    "test": "brunch test"
  },
  "dependencies": {
    "auto-reload-brunch": ">= 1.0 < 1.8",
    "can-compile-brunch": "^0.1.1",
    "clean-css-brunch": "^1.7.1",
    "coffee-script-brunch": "^1.8.1",
    "compass": "^0.1.0",
    "compass-brunch": "0.0.2",
    "css-brunch": "^1.7.0",
    "eco-brunch": "^1.7.5",
    "javascript-brunch": "^1.7.1",
    "sass-brunch": "^1.8.8",
    "stylus-brunch": "^1.8.1",
    "uglify-js-brunch": "^1.7.7"
  }
}
```

To install the application, I ran the following commands:

```
cd kiosk
sudo npm i
sudo npm install -g brunch
sudo gem install sass
sudo gem install compass
```

After receiving the error, I tried running 'npm install' and 'sudo npm install' as suggested, but received the same error.

Can you let me know if this is compatible with a different node or brunch version? Or is there something about this configuration that is incorrect to you can see?

Thanks!

**Comment by aldo-lpz** [comment]
There was a problem with the can-compile-brunch version, I made a minor fix to the npm module and updated the package.json with the new version, It should be error free now.

The new can-compile-brunch version is 0.1.2

I am using:
node 0.12.4
npm 2.10.1
brunch 1.8.3

If you run into more problems with the module, you can remove the can-compile-brunch dependency, as it's just a wrapper around [can-compile](https://github.com/daffl/can-compile), the only difference is that it does not integrate with brunch by default.

**Comment by ninapavlich** [comment]
Thanks for your help!
